version: '1'

services:
  auto-delete:
    build: .
    container_name: auto-delete
    restart: always
    environment:
      TOKEN: xxxxxxxxxxxxx
    networks:
      - auto-delete-network

  mysql:
    image: mysql:8.0.27
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: audel_db
      MYSQL_USER: audel
      MYSQL_PASSWORD: audel_pass
    restart: always
    networks:
      - auto-delete-network

networks:
  auto-delete-network:
    driver: bridge

