version: '1'

services:
  auto-delete:
    build: .
    container_name: auto-delete
    restart: always
    environment:
      TOKEN: "${DISCORD_TOKEN}"
    networks:
      - auto-delete-network

  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - auto-delete-network

networks:
  auto-delete-network:
    driver: bridge

